<h1 align=center><font size = 7>Capstone Project - The Battle of the Neighborhoods</font></h1>

<h1 align=center><font size = 7>"Dress to Impress"</font></h1>

<h2 align=center><font size = 5>Applied Data Science Capstone by IBM</font></h2>

## Table of Contents:

1.  <a href="#item1">Business Problem</a>

2.  <a href="#item2">Data</a>

3.  <a href="#item3">Methodology</a>

4.  <a href="#item4">Results</a>

5.  <a href="#item5">Discussion</a>

<a id='item1'></a>
## Business Problem

Andreea is a vlogger moving to Bucharest, Romania, to follow her dream of opening her own coffee shop. She currently makes her living out of her Youtube and Instagram accounts, making movies about her whereabouts. She is looking to find out which neighbourhood from Bucharest is the most suitable to fit her highly active lifestyle. The neighbourhood should lack too many coffee shops, so that it could embrace her own business. Doing so, she hopes to maximize her chances of success.

The target audience for this project should also be other self-employed people looking for fame and cash-flow generated by their presence in certain places, in the city of Bucharest. Also, people looking to invest in consumer-oriented business should find this study helpful in decided where and why to invest in certain places.

<a id='item1'></a>
## Data

Based on definition of our problem, factors that will influence our decission are:
- diversity of neighbourhood amenities
- closeness of similar neighbourhoods
- number of existing coffee shops in the neighborhood

The data used for this report are sourced using the following:
- Wikipedia page to identify all Neighbourhoods in Bucharest, Romania: https://en.wikipedia.org/wiki/Category:Districts_of_Bucharest
- Foursquare API to find amenities and their type and location in every neighborhood from Bucharest
- Google Maps API geocoding to locate the neighbourhoods

In [128]:
from bs4 import BeautifulSoup
import csv
import pandas as pd
import numpy as np
import requests
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (4.5.1)

In [55]:
source = requests.get('https://en.wikipedia.org/wiki/Category:Districts_of_Bucharest').text 
soup = BeautifulSoup(source, 'lxml')

In [56]:
csv_file = open('bucharest.csv', 'w')
csv_writer = csv.writer(csv_file)
csv_writer.writerow(['Neighbourhood'])

15

In [57]:
mwcg = soup.find_all(class_ = "mw-category-group")
length = len(mwcg) 
for i in range(1, length): 
    lists = mwcg [i].find_all('a')
    for list in lists:
        nbd = list.get('title')
        csv_writer.writerow([nbd])

In [58]:
csv_file.close()

In [116]:
df = pd.read_csv('bucharest.csv')

In [117]:
df.shape

(39, 1)

In [118]:
df.head()

          Neighbourhood
0    Băneasa, Bucharest
1    Berceni, Bucharest
2        Bucureștii Noi
3         Centrul Civic
4  Colentina, Bucharest

In [119]:
df['Neighbourhood'] = df.Neighbourhood.str.replace(', Bucharest,?' , '')

In [120]:
df.head()

    Neighbourhood
0         Băneasa
1         Berceni
2  Bucureștii Noi
3   Centrul Civic
4       Colentina

In [121]:
google_api_key = 'AIzaSyCl7lgEer86yHzMUqF185vPmCus1m-lNzE'

In [125]:
import requests
import json


latitudes = []
longitudes = []
distance = []

for nbd in df["Neighbourhood"] : 
    address = nbd + ", Bucharest,Romania"
    url = 'https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}'.format(address, google_api_key)
    obj = json.loads(requests.get(url).text)
    
    results = obj['results']
    lat = results[0]['geometry']['location']['lat']
    lng = results[0]['geometry']['location']['lng']

    latitudes.append(lat)
    longitudes.append(lng)

In [126]:
df['Latitude'] = latitudes
df['Longitude'] = longitudes

In [127]:
df.head()

    Neighbourhood   Latitude  Longitude
0         Băneasa  44.493726  26.076048
1         Berceni  44.389221  26.118203
2  Bucureștii Noi  44.493619  26.031081
3   Centrul Civic  44.427285  26.092441
4       Colentina  44.465766  26.148647

<a id='item1'></a>
## Methodology

<a id='item1'></a>
## Results

<a id='item1'></a>
## Discussion

## Libraries used:

In [ ]:
import json
from pandas import json_normalize 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from sklearn.cluster import KMeans
import random
import matplotlib.cm as cm
import matplotlib.colors as colors
print('Libraries imported.')

In [ ]:

!pip install folium
from sklearn.cluster import KMeans
!conda install -c conda-forge folium=0.5.0 --yes
import folium
!conda install -c conda-forge geopy --yes
from geopy.geocoders import Nominatim
print('Libraries imported.')